import {appName} from "../app/services/appName";

export const routes = {
  tabNavigator: "Tabs",
  drawerNavigator: "Drawer",
  homeScreen: "Home",
  searchScreen: "Search",
  newListingScreen: "New Listing",
  chatListScreen: "Chats",
  accountScreen: "Account",
  listingDetailScreen: "Listing Detail",
  sendEmailScreen: "Send Email",
  contactUsScreen: "Contact us",
  reportScreen: "Report",
  chatScreen: "Chat",
  chatScreenSingle: "Chatsingle",
  selectLocationScreen: "Location",
  settingsScreen: "Settings",
  loginScreen: "Log In",
  signUpScreen: "Sign Up",
  myListingsScreen: "My Listings",
  myMembershipScreen: "My Membership",
  favouriteScreen: "Favourite",
  myProfileScreen: "My Profile",
  fAQScreen: "FAQ",
  howToSellFastScreen: "How To Sell Fast",
  moreScreen: "More",
  aboutAppScreen: appName,
  selectcategoryScreen: "Select category",
  privacyPolicyScreen: "Privacy Policy",
  Screen: "Licenses",
  tnCScreen: "TnC",
  editPersonalDetailScreen: "Edit Personal Detail",
  editListingScreen: "Edit Listing",
  storeDetailsScreen: "Store Details",
  allStoresScreen: "Stores",
  myStoreScreen: "My Store Settings",
  membershipsScreen: "Membership Packages",
  paymentMethodScreen: "Payment Method",
  promoteScreen: "Promote Ad",
  paymentsScreen: "Payments",
  paymentScreen:"Checkout",
  confirmScreen:"Confirm",
  paymentDetailScreen: "Payment Detail",
  forgotPassScreen: "Forgot Password",
  oTPScreen: "Verification",
  documentsScreen: "My Documents",
  privacynSafetyScreen: "Privacy & Safety",
  hiddenListingsScreen: "Hidden Listings",
  blockedUsersScreen: "Blocked Users",
  paymentScreen:"paymentScreen",
};